language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config -g github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer install

before_deploy:
  - eval $(ssh-agent -s)
  - openssl aes-256-cbc -K $encrypted_fb9206684278_key -iv $encrypted_fb9206684278_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo ${SSH_HOST_KEY} >> ~/.ssh/known_hosts

deploy:
  provider: script
  script: bash bin/deploy.sh
  on:
    branch: master
