language: php

php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install

before_deploy:
  - eval $(ssh-agent -s)
  - openssl aes-256-cbc -K $encrypted_fb9206684278_key -iv $encrypted_fb9206684278_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  script: ssh -o ForwardAgent=yes ${SSH_USER}@${SSH_HOST} "cd /home/www-data/opendata.ch && git pull --rebase --stat && composer update --no-dev --no-interaction --no-progress --optimize-autoloader"
  on:
    branch: master
