---
services:

  web:
    build: .
    depends_on:
      - mysql
    ports:
      - "8000:80"
      - "8001:80"
      - "8002:80"
      - "8003:80"
      - "8004:80"
      - "8005:80"
      - "8006:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: opendata
    ports:
      - "3307:3306"
